name: GitLeaks Secret Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  gitleaks:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      ####################################################
      # Install GitLeaks
      ####################################################

      - name: Install GitLeaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz
          tar -xzf gitleaks_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      ####################################################
      # Scan Repository
      ####################################################

      - name: Run GitLeaks
        run: |
          gitleaks detect \
            --source . \
            --verbose \
            --exit-code 0