name: Trivy Vulnerability Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:

  trivy:

    runs-on: ubuntu-latest

    steps:

      #################################################
      # Checkout
      #################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      #################################################
      # Filesystem Scan
      #################################################

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      #################################################
      # Upload Report
      #################################################

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: .