name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  zap_scan:

    runs-on: ubuntu-latest

    steps:

      ##################################################
      # Checkout
      ##################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      ##################################################
      # Run OWASP ZAP Baseline Scan
      ##################################################

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "https://employee-service-460587643228.asia-south1.run.app"

      ##################################################
      # Upload Report
      ##################################################

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html