name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Cloud Run Service Name"
        required: true
        default: employee-service

      revision:
        description: "Revision to rollback to"
        required: true

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:

  rollback:

    runs-on: ubuntu-latest

    steps:

      ##################################################
      # Checkout Repository
      ##################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      ##################################################
      # Authenticate
      ##################################################

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      ##################################################
      # Rollback
      ##################################################

      - name: Rollback Cloud Run Service
        run: |
          echo "Rolling back ${{ github.event.inputs.service }}"
          echo "Target Revision: ${{ github.event.inputs.revision }}"

          gcloud run services update-traffic \
            ${{ github.event.inputs.service }} \
            --to-revisions=${{ github.event.inputs.revision }}=100 \
            --region=$REGION \
            --project=$PROJECT_ID

      ##################################################
      # Verify
      ##################################################

      - name: Verify Deployment
        run: |
          gcloud run services describe \
            ${{ github.event.inputs.service }} \
            --region=$REGION

      ##################################################
      # Success
      ##################################################

      - name: Success
        run: |
          echo "========================================"
          echo "Rollback Successful"
          echo "========================================"