name: Reusable Build Workflow

on:

  workflow_call:

    inputs:

      service-name:
        required: true
        type: string

      dockerfile:
        required: true
        type: string

      image-name:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      ##################################################
      # Checkout
      ##################################################

      - uses: actions/checkout@v4

      ##################################################
      # Authenticate
      ##################################################

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      ##################################################
      # Configure Docker
      ##################################################

      - run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      ##################################################
      # Build Image
      ##################################################

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/serverless-repo/${{ inputs.image-name }}:latest
          build-args: |
            SERVICE_NAME=${{ inputs.service-name }}

      ##################################################
      # Success
      ##################################################

      - run: |
          echo "Reusable Build Completed Successfully"